return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = {
        'bash',
        'powershell',
        'c',
        'cpp',
        'c_sharp',
        'javascript',
        'typescript',
        'lua',
        'luadoc',
        'vim',
        'vimdoc',
        'angular',
        'html',
        'css',
        'json',
        'jsdoc',
        'python',
        'rust',
        'go',
        'markdown',
        'markdown_inline',
        'yaml',
        'toml',
        'xml',
        'editorconfig',
        'dockerfile',
      },
      sync_install = false,
      auto_install = true,
      indent = {
        enable = true,
      },
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'markdown' },
      },
    })
  end,
}
